// Configuration and constants for all features

export const CONFIG = {
  // Preloader
  PRELOADER_DURATION: 2200,
  PRELOADER_PARTICLES: 16,

  // Parallax
  PARALLAX_STRENGTH: 0.5,
  PARALLAX_SMOOTH: 0.1,

  // Aurora
  AURORA_COLORS: [
    { h: 160, s: 100, l: 50 },
    { h: 200, s: 100, l: 50 },
    { h: 240, s: 100, l: 50 },
    { h: 280, s: 100, l: 50 },
  ],
  AURORA_SPEED: 0.0005,

  // Shooting Stars
  SHOOTING_STAR_COUNT: 3,
  SHOOTING_STAR_INTERVAL: 3000,
  SHOOTING_STAR_SPEED: 0.8,

  // Floating Quotes
  QUOTE_INTERVAL: 25000, // 20-40 seconds
  QUOTE_DISPLAY_TIME: 6000,

  // Cursor
  CURSOR_SIZE: 20,
  CURSOR_GLOW_SIZE: 50,

  // Love Counter
  RELATIONSHIP_START: new Date("2006-07-23T00:00:00"),

  // Day/Night
  DAY_CYCLE_DURATION: 20000, // Real time for demo, would be 86400000 for 24h

  // Colors
  COLORS: {
    pink: "#ff8ecb",
    rose: "#ffb6d0",
    lavender: "#c4b3ff",
    purple: "#8a65ff",
    text: "#fff7fe",
    muted: "#f8dff3",
    bg: "#09030d",
  },

  // Timings
  ANIMATION_DURATION: 0.6,
  ANIMATION_EASE: "ease-out",

  // Performance
  MAX_PARTICLES: 200,
  ENABLE_PARALLAX: true,
  ENABLE_AURORA: true,
  ENABLE_STARS: true,
};

// Love Quotes - 100 romantic quotes
export const LOVE_QUOTES = [
  "You are my favorite chapter.",
  "My forever begins with you.",
  "You complete my universe.",
  "I'd choose you in every lifetime.",
  "Your smile is my favorite view.",
  "In your eyes, I found my home.",
  "Every moment with you is a blessing.",
  "You're my greatest adventure.",
  "I love you more than yesterday, less than tomorrow.",
  "You make my heart skip a beat.",
  "Forever doesn't seem long enough with you.",
  "You are my happy place.",
  "My heart chose you before my mind could understand.",
  "With you, I found what I've been looking for.",
  "You are the love I was searching for.",
  "Every love story is beautiful, but ours is my favorite.",
  "You make ordinary moments magical.",
  "I never knew what love was until I met you.",
  "You're my person.",
  "In a world full of chaos, you are my peace.",
  "I love you more than coffee, and you know that's true.",
  "You are my dream come true.",
  "With you, I feel alive.",
  "You are the best decision I ever made.",
  "My love for you is endless.",
  "You are my greatest blessing.",
  "I choose you, every single day.",
  "You complete me in ways you'll never know.",
  "Forever with you sounds like a dream.",
  "You are everything I've ever wanted.",
  "Your love is my favorite feeling.",
  "I'm so grateful you're in my life.",
  "You make life worth living.",
  "I fall in love with you more every day.",
  "You are my forever and always.",
  "With you, everything feels right.",
  "You are my greatest love story.",
  "I love every part of you.",
  "You are my soulmate.",
  "My heart is yours forever.",
  "You make my heart flutter.",
  "In you, I found my true love.",
  "You are my happily ever after.",
  "I love you to the moon and back.",
  "You are my favorite person.",
  "With you is my favorite place to be.",
  "You are my forever person.",
  "I love you with all my heart.",
  "You are the answer to all my prayers.",
  "My love for you is infinite.",
  "You are my greatest treasure.",
  "I'm forever grateful for you.",
  "You make my dreams come true.",
  "You are my everything.",
  "I love you now, I'll love you forever.",
  "You are my reason to smile.",
  "With you, I feel complete.",
  "You are my happy ending.",
  "I choose you every day.",
  "Your love is my strength.",
  "You are my favorite person in the world.",
  "I'm so in love with you.",
  "You are my heart's desire.",
  "With you, I'm home.",
  "You are my greatest blessing.",
  "I love you more than words can say.",
  "You are my soulmate, my best friend, my forever.",
  "Every day with you is a gift.",
  "You are my love, my life, my everything.",
  "I'm madly in love with you.",
  "You are my forever love.",
  "With you, anything is possible.",
  "You are my greatest adventure.",
  "I love you more today than yesterday.",
  "You are my dream, my reality, my forever.",
  "My heart belongs to you.",
  "You are my happily ever after.",
  "I love you with every fiber of my being.",
  "You are my forever person.",
  "With you, I found my soulmate.",
  "You are my greatest joy.",
  "I love you infinitely.",
  "You are my person, now and forever.",
  "Every moment with you is precious.",
  "You are my love, my light, my life.",
  "I'm forever yours.",
  "You are my forever and always.",
  "I love you beyond measure.",
  "You are my greatest happiness.",
  "With you, I feel complete.",
  "You are my soulmate.",
  "I love you more than anything.",
  "You are my everything.",
  "My heart is yours.",
  "You are my greatest love.",
  "I'm so lucky to have you.",
  "You are my forever love.",
  "I love you endlessly.",
  "You are my dream come true.",
  "With you is where I belong.",
];

// Memory Popups - 100 romantic memories
export const MEMORY_POPUPS = [
  "I still remember your smile ❤️",
  "Our first conversation...",
  "Best day ever.",
  "Your laughter echoes in my heart.",
  "That moment changed everything.",
  "You are my favorite memory.",
  "Every moment with you is unforgettable.",
  "I'll never forget that day.",
  "Your love made me believe in forever.",
  "Best decision of my life.",
  "That kiss... wow.",
  "You complete every memory.",
  "Every day with you is a precious memory.",
  "I cherish every moment with you.",
  "My favorite memories have you in them.",
  "You are the best thing that happened to me.",
  "I'm grateful for every moment we've shared.",
  "Your love is my greatest memory.",
  "I could never forget you.",
  "You are my most beautiful memory.",
  "Every kiss with you is a memory.",
  "Our love story is my favorite.",
  "You make every day memorable.",
  "I love remembering us.",
  "My favorite person, my favorite memories.",
  "With you, every moment is special.",
  "You are unforgettable.",
  "I love our love story.",
  "Every memory with you is treasured.",
  "You are my greatest gift.",
  "I'll always remember this moment.",
  "Your love is unforgettable.",
  "I'm grateful for every memory with you.",
  "You made my life beautiful.",
  "I love you more with every memory.",
  "Our love is my greatest memory.",
  "I'll never forget how you make me feel.",
  "You are my most cherished memory.",
  "Every day with you is a blessing.",
  "I love the memories we're making.",
  "You are my forever memory.",
  "I cherish every moment with you.",
  "Your smile is my favorite memory.",
  "I'm so lucky to have these memories with you.",
  "You are my greatest treasure.",
  "Every moment with you matters.",
  "I love creating memories with you.",
  "You are the best part of my memories.",
  "I'm grateful for every moment.",
  "You make life unforgettable.",
];

// Wish Jar - 200 romantic messages
export const WISH_JAR_MESSAGES = [
  "I wish to spend forever with you ❤️",
  "May every day be as beautiful as you.",
  "I wish to make you smile forever.",
  "You are my greatest wish come true.",
  "I wish to love you more every day.",
  "May my love for you never fade.",
  "I wish to grow old with you.",
  "You are all I wish for.",
  "I wish for endless moments with you.",
  "May our love last forever.",
  "I wish you knew how much you mean to me.",
  "You are my wish upon a star.",
  "I wish to hold your hand always.",
  "May you always feel my love.",
  "I wish to wake up next to you forever.",
  "You are my greatest blessing.",
  "I wish to make all your dreams come true.",
  "May love guide us always.",
  "I wish you happiness beyond measure.",
  "You are my answered prayer.",
  "I wish to be your forever.",
  "May our love grow stronger each day.",
  "I wish to make you feel loved every single day.",
  "You are my heart's greatest wish.",
  "I wish for a lifetime of love with you.",
  "May you always know how much I love you.",
  "I wish to be your person.",
  "You are my wish, my hope, my love.",
  "I wish to spend my life making you happy.",
  "May our story never end.",
  "I wish you could feel how much I love you.",
  "You are my favorite wish.",
  "I wish to love you unconditionally.",
  "May every moment with you be special.",
  "I wish to be yours forever.",
  "You are the answer to my wishes.",
  "I wish love upon your beautiful heart.",
  "May you always be mine.",
  "I wish to cherish you always.",
  "You are my greatest wish.",
  "I wish our love to be eternal.",
  "May I never stop loving you.",
  "I wish to be your everything.",
  "You are my wish come to life.",
  "I wish for countless moments of joy with you.",
  "May our love transcend all.",
  "I wish to hold you close always.",
  "You are my wish upon the stars.",
  "I wish my love could fill your heart.",
  "May you feel my love forever.",
  "I wish for eternity with you.",
  "You are my only wish.",
  "I wish to make you my forever.",
  "May love conquer all.",
  "I wish you infinite happiness.",
  "You are my greatest wish.",
  "I wish to write our love story forever.",
  "May every kiss be like our first.",
  "I wish to never let you go.",
  "You are my wish made real.",
  "I wish to love you more tomorrow.",
  "May our hearts beat as one.",
  "I wish you could see yourself through my eyes.",
  "You are my most treasured wish.",
  "I wish to be your sanctuary.",
  "May love light our way.",
  "I wish to be your strength.",
  "You are my forever wish.",
  "I wish to cherish every moment with you.",
  "May our love be timeless.",
  "I wish you felt how deeply I love you.",
  "You are my wish, my dream, my reality.",
  "I wish for us to never part.",
  "May love always find us.",
  "I wish to see the world through your eyes.",
  "You are my wish upon a thousand stars.",
  "I wish my love could touch your soul.",
  "May you always choose me.",
  "I wish to be your forever person.",
  "You are my greatest wish.",
  "I wish for a lifetime of love and laughter.",
  "May every day be Valentine's Day with you.",
  "I wish to write our love story.",
  "You are my wish, my heart, my soul.",
  "I wish to love you beyond forever.",
  "May our love never fade.",
  "I wish to make every moment count.",
  "You are my answered wish.",
  "I wish for infinity with you.",
  "May love guide us always.",
  "I wish you knew how special you are.",
  "You are my greatest wish.",
];

// Love Achievements
export const ACHIEVEMENTS = [
  { id: "opened_gift", title: "Gift Hunter", description: "Opened the gift box", emoji: "🎁" },
  { id: "read_letter", title: "Love Letters", description: "Read the love letter", emoji: "💌" },
  { id: "blew_candle", title: "Wish Master", description: "Blew the birthday candle", emoji: "🎂" },
  { id: "viewed_gallery", title: "Memory Keeper", description: "Viewed the photo gallery", emoji: "📸" },
  { id: "heart_clicks_10", title: "Heart Starter", description: "Clicked heart 10 times", emoji: "❤️" },
  { id: "heart_clicks_50", title: "Heart Believer", description: "Clicked heart 50 times", emoji: "💖" },
  { id: "heart_clicks_100", title: "Heart Master", description: "Clicked heart 100 times", emoji: "💗" },
  { id: "constellation", title: "Star Gazer", description: "Found the love constellation", emoji: "⭐" },
  { id: "secret_message", title: "Secret Seeker", description: "Unlocked secret message", emoji: "🔓" },
  { id: "grand_finale", title: "Forever Legend", description: "Reached the grand finale", emoji: "👑" },
];
